# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-02 18:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linhas',
            fields=[
                ('nome_linha', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rota_padrao', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'linhas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motoristas',
            fields=[
                ('id_motorista', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, verbose_name='Informe seu nome:')),
                ('cpf', models.IntegerField(verbose_name='Informe seu CPF:')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'motoristas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id_posicao', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('data', models.DateField(auto_now_add=True)),
                ('id_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Motoristas')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'posicao',
                'managed': True,
            },
        ),
    ]
