# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-16 19:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linhas',
            fields=[
                ('nome_linha', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('rota_padrao', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'linhas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Motoristas_cadastrados',
            fields=[
                ('nome', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(verbose_name='Informe seu CPF:')),
            ],
            options={
                'db_table': 'motoristas_cadastrados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id_posicao', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posicao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rota_atual',
            fields=[
                ('id_rota_atual', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('id_posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Posicao')),
            ],
            options={
                'db_table': 'rota_atual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id_viagem', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(verbose_name='Informe seu CPF:')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Motoristas_cadastrados')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'viagens',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='rota_atual',
            name='id_viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens'),
        ),
        migrations.AddField(
            model_name='rota_atual',
            name='nome_linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='id_viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='nome_linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas'),
        ),
    ]
