# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-05 22:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercampi', '0004_remove_posicao_atual_id_posicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao_atualExtra',
            fields=[
                ('id_pa', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'Posicao_atualExtra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao_atualFerias',
            fields=[
                ('id_pa', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'Posicao_atualFerias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao_atualII',
            fields=[
                ('id_pa', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'Posicao_atualII',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao_atualIII',
            fields=[
                ('id_pa', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'Posicao_atualIII',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Posicao_atualIV',
            fields=[
                ('id_pa', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Viagens')),
                ('nome_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercampi.Linhas')),
            ],
            options={
                'db_table': 'Posicao_atualIV',
                'managed': True,
            },
        ),
    ]
